/**
 * Pipeline Session Detector
 *
 * Detects and loads squiggy-session.json files generated by external pipelines
 * (e.g., aa-tRNA pipeline). Pipeline sessions use paths relative to the session
 * file's location, unlike standard sessions which use absolute paths.
 */

import * as vscode from 'vscode';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as crypto from 'crypto';
import { SessionState, SampleSessionState } from '../types/squiggy-session-types';
import { PathResolver } from './path-resolver';
import { SessionStateManager } from './session-state-manager';
import { logger } from '../utils/logger';

/** Severity of a file issue during session validation */
export type SessionFileIssueSeverity = 'critical' | 'warning';

/** A single file issue found during session validation */
export interface SessionFileIssue {
    sampleName: string;
    filePath: string;
    fileType: 'POD5' | 'BAM' | 'FASTA' | 'BAI';
    severity: SessionFileIssueSeverity;
}

/** Result of validating all file paths in a session */
export interface SessionFileValidationResult {
    valid: boolean;
    issues: SessionFileIssue[];
}

/** Default session filename generated by pipelines */
const PIPELINE_SESSION_FILENAME = 'squiggy-session.json';

/** Workspace state key for user preference */
const PIPELINE_SESSION_PREFERENCE_KEY = 'squiggy.pipelineSessionAutoLoad';

/** Subdirectories to search for pipeline session files */
const SEARCH_SUBDIRS = ['', 'results', 'output', 'analysis'];

/** File size threshold (1GB) above which MD5 validation is skipped */
const LARGE_FILE_THRESHOLD = 1024 * 1024 * 1024; // 1GB

/** User preferences for auto-load behavior */
type AutoLoadPreference = 'ask' | 'skip';

/**
 * Result of pipeline session detection
 */
export interface PipelineSessionDetectionResult {
    found: boolean;
    sessionPath?: string;
    sessionDir?: string;
    session?: SessionState;
    error?: string;
}

/**
 * Result of checksum validation
 */
export interface ChecksumValidationResult {
    valid: boolean;
    mismatches: Array<{
        filePath: string;
        expected?: string;
        actual?: string;
        reason: 'missing' | 'changed' | 'new';
    }>;
}

/**
 * Detect pipeline session file in workspace folders
 *
 * Scans all workspace folders and common subdirectories for a squiggy-session.json file.
 * Searches in: workspace root, results/, output/, analysis/
 * Returns the first match found.
 *
 * @returns Detection result with session path and parsed content if found
 */
export async function detectPipelineSession(): Promise<PipelineSessionDetectionResult> {
    const workspaceFolders = vscode.workspace.workspaceFolders;

    if (!workspaceFolders || workspaceFolders.length === 0) {
        return { found: false };
    }

    // Scan each workspace folder and common subdirectories for session file
    for (const folder of workspaceFolders) {
        for (const subdir of SEARCH_SUBDIRS) {
            const sessionPath = path.join(folder.uri.fsPath, subdir, PIPELINE_SESSION_FILENAME);

            try {
                // Check if file exists
                await fs.access(sessionPath);

                // Read and parse session
                const json = await fs.readFile(sessionPath, 'utf-8');
                const session = JSON.parse(json) as SessionState;

                // Validate session schema
                const validation = SessionStateManager.validateSession(session);
                if (!validation.valid) {
                    logger.warning(
                        `Pipeline session at ${sessionPath} has invalid schema: ${validation.errors.join(', ')}`
                    );
                    continue; // Try next subdirectory
                }

                const location = subdir ? `${folder.name}/${subdir}` : folder.name;
                logger.info(`Detected pipeline session at ${sessionPath} (in ${location})`);

                return {
                    found: true,
                    sessionPath,
                    sessionDir: path.dirname(sessionPath),
                    session,
                };
            } catch (_error) {
                // File doesn't exist or can't be read - continue to next location
                continue;
            }
        }
    }

    return { found: false };
}

/**
 * Resolve all relative paths in a session to absolute paths
 *
 * Pipeline sessions store paths relative to the session file's directory.
 * This function converts all paths to absolute paths for loading.
 *
 * @param session Session state with potentially relative paths
 * @param sessionFileDir Directory containing the session file
 * @returns New SessionState with all paths resolved to absolute
 */
export function resolveAllPaths(session: SessionState, sessionFileDir: string): SessionState {
    const resolvedSamples: { [sampleName: string]: SampleSessionState } = {};

    for (const [sampleName, sampleData] of Object.entries(session.samples)) {
        // Resolve POD5 paths
        const resolvedPod5Paths = sampleData.pod5Paths.map((p) =>
            PathResolver.resolveSessionRelativePath(p, sessionFileDir)
        );

        // Resolve BAM path if present
        const resolvedBamPath = sampleData.bamPath
            ? PathResolver.resolveSessionRelativePath(sampleData.bamPath, sessionFileDir)
            : undefined;

        // Resolve FASTA path if present
        const resolvedFastaPath = sampleData.fastaPath
            ? PathResolver.resolveSessionRelativePath(sampleData.fastaPath, sessionFileDir)
            : undefined;

        resolvedSamples[sampleName] = {
            pod5Paths: resolvedPod5Paths,
            bamPath: resolvedBamPath,
            fastaPath: resolvedFastaPath,
        };
    }

    // Also update fileChecksums keys to absolute paths
    let resolvedChecksums: SessionState['fileChecksums'] | undefined;
    if (session.fileChecksums) {
        resolvedChecksums = {};
        for (const [filePath, info] of Object.entries(session.fileChecksums)) {
            const resolvedPath = PathResolver.resolveSessionRelativePath(filePath, sessionFileDir);
            resolvedChecksums[resolvedPath] = info;
        }
    }

    return {
        ...session,
        samples: resolvedSamples,
        fileChecksums: resolvedChecksums,
    };
}

/**
 * Validate file checksums against stored values
 *
 * Compares MD5 checksums of files against values stored in the session.
 * For files larger than 1GB, only existence and size are validated (no MD5)
 * to avoid memory exhaustion with multi-GB POD5 files.
 *
 * @param session Session state with fileChecksums (paths should be absolute)
 * @returns Validation result with list of mismatched files
 */
export async function validateChecksums(session: SessionState): Promise<ChecksumValidationResult> {
    const mismatches: ChecksumValidationResult['mismatches'] = [];

    if (!session.fileChecksums) {
        // No checksums stored, assume valid
        return { valid: true, mismatches: [] };
    }

    for (const [filePath, expectedInfo] of Object.entries(session.fileChecksums)) {
        try {
            // Get file stats to check existence and size
            const stats = await fs.stat(filePath);

            // For large files (>1GB), skip MD5 and only validate existence + size
            if (stats.size > LARGE_FILE_THRESHOLD) {
                if (expectedInfo.size !== undefined && expectedInfo.size !== stats.size) {
                    mismatches.push({
                        filePath,
                        expected: `size ${expectedInfo.size}`,
                        actual: `size ${stats.size}`,
                        reason: 'changed',
                    });
                }
                // File exists and size matches (or no size stored) - skip MD5
                logger.debug(
                    `Skipping MD5 validation for large file (${(stats.size / 1024 / 1024 / 1024).toFixed(1)} GB): ${path.basename(filePath)}`
                );
                continue;
            }

            // For smaller files, compute MD5 as before
            const content = await fs.readFile(filePath);
            const hash = crypto.createHash('md5');
            hash.update(content);
            const actualMd5 = hash.digest('hex');

            // Compare checksums
            if (expectedInfo.md5 && expectedInfo.md5 !== actualMd5) {
                mismatches.push({
                    filePath,
                    expected: expectedInfo.md5,
                    actual: actualMd5,
                    reason: 'changed',
                });
            }
        } catch (_error) {
            // File doesn't exist or can't be read
            mismatches.push({
                filePath,
                expected: expectedInfo.md5,
                reason: 'missing',
            });
        }
    }

    // Check for new files in session that don't have checksums
    for (const sampleData of Object.values(session.samples)) {
        for (const pod5Path of sampleData.pod5Paths) {
            if (!session.fileChecksums[pod5Path]) {
                mismatches.push({
                    filePath: pod5Path,
                    reason: 'new',
                });
            }
        }
        if (sampleData.bamPath && !session.fileChecksums[sampleData.bamPath]) {
            mismatches.push({
                filePath: sampleData.bamPath,
                reason: 'new',
            });
        }
        if (sampleData.fastaPath && !session.fileChecksums[sampleData.fastaPath]) {
            mismatches.push({
                filePath: sampleData.fastaPath,
                reason: 'new',
            });
        }
    }

    return {
        valid: mismatches.length === 0,
        mismatches,
    };
}

/**
 * Get user's auto-load preference from global state
 *
 * @param context Extension context for accessing global state
 * @returns User's preference ('ask' or 'skip')
 */
export function getAutoLoadPreference(context: vscode.ExtensionContext): AutoLoadPreference {
    return context.globalState.get<AutoLoadPreference>(PIPELINE_SESSION_PREFERENCE_KEY, 'ask');
}

/**
 * Set user's auto-load preference in global state
 *
 * @param context Extension context for accessing global state
 * @param preference Preference to store
 */
export async function setAutoLoadPreference(
    context: vscode.ExtensionContext,
    preference: AutoLoadPreference
): Promise<void> {
    await context.globalState.update(PIPELINE_SESSION_PREFERENCE_KEY, preference);
}

/**
 * Show checksum mismatch warning to user
 *
 * @param mismatches List of files with checksum issues
 * @returns true if user wants to continue loading, false otherwise
 */
export async function showChecksumWarning(
    mismatches: ChecksumValidationResult['mismatches']
): Promise<boolean> {
    const changedFiles = mismatches.filter((m) => m.reason === 'changed');
    const missingFiles = mismatches.filter((m) => m.reason === 'missing');

    let message = 'Some files in the pipeline session have changed:\n';

    if (changedFiles.length > 0) {
        message += `\nModified files (${changedFiles.length}):\n`;
        message += changedFiles.map((m) => `  - ${path.basename(m.filePath)}`).join('\n');
    }

    if (missingFiles.length > 0) {
        message += `\nMissing files (${missingFiles.length}):\n`;
        message += missingFiles.map((m) => `  - ${path.basename(m.filePath)}`).join('\n');
    }

    message += '\n\nContinue loading anyway?';

    const response = await vscode.window.showWarningMessage(
        message,
        { modal: true },
        'Load Anyway',
        'Cancel'
    );

    return response === 'Load Anyway';
}

/**
 * Validate all file paths in a session before loading
 *
 * Checks every POD5/BAM/FASTA/BAI path with fs.access(). Returns a list of
 * issues categorized by severity:
 * - Missing POD5 → critical (sample can't load without it)
 * - Missing BAM/FASTA/BAI → warning (sample loads without alignments/reference)
 *
 * @param session Session state with absolute paths
 * @returns Validation result with list of issues
 */
export async function validateSessionFiles(
    session: SessionState
): Promise<SessionFileValidationResult> {
    const issues: SessionFileIssue[] = [];

    for (const [sampleName, sampleData] of Object.entries(session.samples)) {
        // Check POD5 paths
        for (const pod5Path of sampleData.pod5Paths || []) {
            // Skip special path prefixes that get resolved later
            if (pod5Path.startsWith('<package:') || pod5Path.includes('${extensionPath}')) {
                continue;
            }
            try {
                await fs.access(pod5Path);
            } catch {
                issues.push({
                    sampleName,
                    filePath: pod5Path,
                    fileType: 'POD5',
                    severity: 'critical',
                });
            }
        }

        // Check BAM path
        if (sampleData.bamPath) {
            const bamPath = sampleData.bamPath;
            if (!bamPath.startsWith('<package:') && !bamPath.includes('${extensionPath}')) {
                try {
                    await fs.access(bamPath);
                } catch {
                    issues.push({
                        sampleName,
                        filePath: bamPath,
                        fileType: 'BAM',
                        severity: 'warning',
                    });
                }

                // Check BAM index
                const baiPath = `${bamPath}.bai`;
                try {
                    await fs.access(baiPath);
                } catch {
                    issues.push({
                        sampleName,
                        filePath: baiPath,
                        fileType: 'BAI',
                        severity: 'warning',
                    });
                }
            }
        }

        // Check FASTA path
        if (sampleData.fastaPath) {
            const fastaPath = sampleData.fastaPath;
            if (!fastaPath.startsWith('<package:') && !fastaPath.includes('${extensionPath}')) {
                try {
                    await fs.access(fastaPath);
                } catch {
                    issues.push({
                        sampleName,
                        filePath: fastaPath,
                        fileType: 'FASTA',
                        severity: 'warning',
                    });
                }
            }
        }
    }

    return { valid: issues.length === 0, issues };
}

/**
 * Show a consolidated validation report to the user
 *
 * Groups issues by severity and shows one modal dialog instead of per-file dialogs.
 * Critical issues (missing POD5) cause samples to be skipped entirely.
 * Warning issues (missing BAM/FASTA) let samples load without those files.
 *
 * @param issues List of file issues from validateSessionFiles()
 * @returns true if user chose "Load Available", false if cancelled
 */
export async function showSessionValidationReport(issues: SessionFileIssue[]): Promise<boolean> {
    const critical = issues.filter((i) => i.severity === 'critical');
    const warnings = issues.filter((i) => i.severity === 'warning');

    // Count unique affected samples per severity
    const criticalSamples = new Set(critical.map((i) => i.sampleName));
    const warningSamples = new Set(warnings.map((i) => i.sampleName));

    let message = 'Some files in this session are missing:\n';

    if (criticalSamples.size > 0) {
        message += `\n${criticalSamples.size} sample(s) will be skipped (missing POD5):\n`;
        for (const name of criticalSamples) {
            message += `  - ${name}\n`;
        }
    }

    if (warningSamples.size > 0) {
        message += `\n${warningSamples.size} sample(s) will load without alignments/reference:\n`;
        for (const name of warningSamples) {
            const sampleWarnings = warnings.filter((i) => i.sampleName === name);
            const types = [...new Set(sampleWarnings.map((i) => i.fileType))].join(', ');
            message += `  - ${name} (missing ${types})\n`;
        }
    }

    const response = await vscode.window.showWarningMessage(
        message,
        { modal: true },
        'Load Available',
        'Cancel'
    );

    return response === 'Load Available';
}

/**
 * Strip missing files from session data so restoreSampleWithProgress() never encounters them
 *
 * - Critical (missing POD5): Removes the entire sample from session.samples
 * - Warning (missing BAM): Sets sampleData.bamPath = undefined
 * - Warning (missing FASTA): Sets sampleData.fastaPath = undefined
 * - Warning (missing BAI): Sets sampleData.bamPath = undefined (BAM unusable without index)
 *
 * Mutates session in place.
 *
 * @param session Session state to modify
 * @param issues Issues from validateSessionFiles()
 * @returns Number of samples removed entirely
 */
export function stripMissingFiles(session: SessionState, issues: SessionFileIssue[]): number {
    // Collect samples that must be removed entirely (missing POD5)
    const samplesToRemove = new Set(
        issues.filter((i) => i.severity === 'critical').map((i) => i.sampleName)
    );

    // Remove critical samples
    for (const sampleName of samplesToRemove) {
        delete session.samples[sampleName];
    }

    // Handle warnings: strip missing optional files from remaining samples
    const warnings = issues.filter(
        (i) => i.severity === 'warning' && !samplesToRemove.has(i.sampleName)
    );

    for (const issue of warnings) {
        const sampleData = session.samples[issue.sampleName];
        if (!sampleData) continue;

        if (issue.fileType === 'BAM' || issue.fileType === 'BAI') {
            sampleData.bamPath = undefined;
        } else if (issue.fileType === 'FASTA') {
            sampleData.fastaPath = undefined;
        }
    }

    return samplesToRemove.size;
}

/**
 * Browse for a pipeline session file manually
 *
 * @returns Path to selected session file, or undefined if cancelled
 */
export async function browsePipelineSession(): Promise<string | undefined> {
    const uris = await vscode.window.showOpenDialog({
        canSelectMany: false,
        filters: {
            'Squiggy Session': ['json'],
            'All Files': ['*'],
        },
        title: 'Select Pipeline Session File',
    });

    if (!uris || uris.length === 0) {
        return undefined;
    }

    return uris[0].fsPath;
}
